//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proget_Stage_Principame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prospect
    {
        public Prospect()
        {
            this.LActionProspections = new HashSet<LActionProspection>();
        }
    
        public int code { get; set; }
        public string Nom { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public string Titre { get; set; }
        public string Branche { get; set; }
        public string Demarcheure { get; set; }
        public string Adresse { get; set; }
        public string Observation { get; set; }
        public string ville { get; set; }
        public string Telephone { get; set; }
        public string Profession_Activité { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<LActionProspection> LActionProspections { get; set; }
    }
}
